[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.5.2",
    "requests>=2.32.4",
]
[tool.poetry.dependencies]
python = "^3.10"
pillow = "^10.0.0"